version: '3.9'

services:
  nginx:
    build: ./.docker/nginx
    volumes:
      - ./:/var/www/project
    ports:
      -   "8080:80"
    links:
      -   php

  mariadb:
    image: mariadb:latest
    #command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: warframe
      MYSQL_DATABASE: warframe
      MYSQL_USER: warframe
      MYSQL_PASSWORD: warframe
    volumes:
      - db:/var/lib/mysql

  php:
    build: ./.docker/php
    volumes:
      - ./:/var/www/project
      - ./.docker/php/ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.d"

volumes:
  db: