<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220822141539 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE weapon');
        $this->addSql('ALTER TABLE firearm CHANGE unique_name unique_name VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(2000) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE patchlogs patchlogs JSON DEFAULT NULL, CHANGE components components JSON DEFAULT NULL, CHANGE introduced introduced JSON DEFAULT NULL, CHANGE estimated_vault_date estimated_vault_date VARCHAR(255) DEFAULT NULL, CHANGE polarities polarities JSON DEFAULT NULL, CHANGE tags tags JSON DEFAULT NULL, CHANGE market_cost market_cost VARCHAR(255) DEFAULT NULL, CHANGE bp_cost bp_cost VARCHAR(255) DEFAULT NULL, CHANGE attacks attacks JSON DEFAULT NULL, CHANGE wikia_thumbnail wikia_thumbnail VARCHAR(255) DEFAULT NULL, CHANGE wikia_url wikia_url VARCHAR(255) DEFAULT NULL, CHANGE critical_chance critical_chance DOUBLE PRECISION DEFAULT NULL, CHANGE critical_multiplier critical_multiplier DOUBLE PRECISION DEFAULT NULL, CHANGE fire_rate fire_rate DOUBLE PRECISION DEFAULT NULL, CHANGE omega_attenuation omega_attenuation DOUBLE PRECISION DEFAULT NULL, CHANGE proc_chance proc_chance DOUBLE PRECISION DEFAULT NULL, CHANGE release_date release_date VARCHAR(255) DEFAULT NULL, CHANGE vault_date vault_date VARCHAR(255) DEFAULT NULL, CHANGE damage_per_shot damage_per_shot JSON DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE parents parents JSON DEFAULT NULL, CHANGE accuracy accuracy DOUBLE PRECISION DEFAULT NULL, CHANGE multishot multishot DOUBLE PRECISION DEFAULT NULL, CHANGE noise noise VARCHAR(255) DEFAULT NULL, CHANGE trigger_type trigger_type VARCHAR(255) DEFAULT NULL, CHANGE reload_time reload_time DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE melee CHANGE unique_name unique_name VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(2000) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE patchlogs patchlogs JSON DEFAULT NULL, CHANGE components components JSON DEFAULT NULL, CHANGE introduced introduced JSON DEFAULT NULL, CHANGE estimated_vault_date estimated_vault_date VARCHAR(255) DEFAULT NULL, CHANGE polarities polarities JSON DEFAULT NULL, CHANGE tags tags JSON DEFAULT NULL, CHANGE market_cost market_cost VARCHAR(255) DEFAULT NULL, CHANGE bp_cost bp_cost VARCHAR(255) DEFAULT NULL, CHANGE attacks attacks JSON DEFAULT NULL, CHANGE wikia_thumbnail wikia_thumbnail VARCHAR(255) DEFAULT NULL, CHANGE wikia_url wikia_url VARCHAR(255) DEFAULT NULL, CHANGE critical_chance critical_chance DOUBLE PRECISION DEFAULT NULL, CHANGE critical_multiplier critical_multiplier DOUBLE PRECISION DEFAULT NULL, CHANGE fire_rate fire_rate DOUBLE PRECISION DEFAULT NULL, CHANGE omega_attenuation omega_attenuation DOUBLE PRECISION DEFAULT NULL, CHANGE proc_chance proc_chance DOUBLE PRECISION DEFAULT NULL, CHANGE release_date release_date VARCHAR(255) DEFAULT NULL, CHANGE vault_date vault_date VARCHAR(255) DEFAULT NULL, CHANGE damage_per_shot damage_per_shot JSON DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE parents parents JSON DEFAULT NULL, CHANGE follow_through follow_through DOUBLE PRECISION DEFAULT NULL, CHANGE attack_range attack_range DOUBLE PRECISION DEFAULT NULL, CHANGE stance_polarity stance_polarity VARCHAR(255) DEFAULT NULL, CHANGE wind_up wind_up DOUBLE PRECISION DEFAULT NULL, CHANGE drops drops JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE weapon (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, unique_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, description VARCHAR(2000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, tradable TINYINT(1) DEFAULT NULL, category VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, product_category VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, patchlogs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, components LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, introduced LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, estimated_vault_date VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, polarities LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, tags LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, vaulted TINYINT(1) DEFAULT NULL, market_cost VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, bp_cost VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, attacks LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, mastery_req INT DEFAULT NULL, build_price INT DEFAULT NULL, build_time INT DEFAULT NULL, skip_build_time_price INT DEFAULT NULL, build_quantity INT DEFAULT NULL, consume_on_build TINYINT(1) DEFAULT NULL, wikia_thumbnail VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, wikia_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, critical_chance DOUBLE PRECISION DEFAULT \'NULL\', critical_multiplier DOUBLE PRECISION DEFAULT \'NULL\', disposition INT DEFAULT NULL, fire_rate DOUBLE PRECISION DEFAULT \'NULL\', omega_attenuation DOUBLE PRECISION DEFAULT \'NULL\', proc_chance DOUBLE PRECISION DEFAULT \'NULL\', release_date VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, slot INT DEFAULT NULL, total_damage INT DEFAULT NULL, vault_date VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, damage_per_shot LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, image_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, parents LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, max_level_cap INT DEFAULT NULL, item_count INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE user');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE melee CHANGE unique_name unique_name VARCHAR(255) DEFAULT \'NULL\', CHANGE description description VARCHAR(2000) DEFAULT \'NULL\', CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE category category VARCHAR(255) DEFAULT \'NULL\', CHANGE patchlogs patchlogs LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE components components LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE introduced introduced LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE estimated_vault_date estimated_vault_date VARCHAR(255) DEFAULT \'NULL\', CHANGE polarities polarities LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE tags tags LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE market_cost market_cost VARCHAR(255) DEFAULT \'NULL\', CHANGE bp_cost bp_cost VARCHAR(255) DEFAULT \'NULL\', CHANGE attacks attacks LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE wikia_thumbnail wikia_thumbnail VARCHAR(255) DEFAULT \'NULL\', CHANGE wikia_url wikia_url VARCHAR(255) DEFAULT \'NULL\', CHANGE critical_chance critical_chance DOUBLE PRECISION DEFAULT \'NULL\', CHANGE critical_multiplier critical_multiplier DOUBLE PRECISION DEFAULT \'NULL\', CHANGE fire_rate fire_rate DOUBLE PRECISION DEFAULT \'NULL\', CHANGE omega_attenuation omega_attenuation DOUBLE PRECISION DEFAULT \'NULL\', CHANGE proc_chance proc_chance DOUBLE PRECISION DEFAULT \'NULL\', CHANGE release_date release_date VARCHAR(255) DEFAULT \'NULL\', CHANGE vault_date vault_date VARCHAR(255) DEFAULT \'NULL\', CHANGE damage_per_shot damage_per_shot LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\', CHANGE parents parents LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE follow_through follow_through DOUBLE PRECISION DEFAULT \'NULL\', CHANGE attack_range attack_range DOUBLE PRECISION DEFAULT \'NULL\', CHANGE stance_polarity stance_polarity VARCHAR(255) DEFAULT \'NULL\', CHANGE wind_up wind_up DOUBLE PRECISION DEFAULT \'NULL\', CHANGE drops drops LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE firearm CHANGE unique_name unique_name VARCHAR(255) DEFAULT \'NULL\', CHANGE description description VARCHAR(2000) DEFAULT \'NULL\', CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE category category VARCHAR(255) DEFAULT \'NULL\', CHANGE patchlogs patchlogs LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE components components LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE introduced introduced LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE estimated_vault_date estimated_vault_date VARCHAR(255) DEFAULT \'NULL\', CHANGE polarities polarities LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE tags tags LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE market_cost market_cost VARCHAR(255) DEFAULT \'NULL\', CHANGE bp_cost bp_cost VARCHAR(255) DEFAULT \'NULL\', CHANGE attacks attacks LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE wikia_thumbnail wikia_thumbnail VARCHAR(255) DEFAULT \'NULL\', CHANGE wikia_url wikia_url VARCHAR(255) DEFAULT \'NULL\', CHANGE critical_chance critical_chance DOUBLE PRECISION DEFAULT \'NULL\', CHANGE critical_multiplier critical_multiplier DOUBLE PRECISION DEFAULT \'NULL\', CHANGE fire_rate fire_rate DOUBLE PRECISION DEFAULT \'NULL\', CHANGE omega_attenuation omega_attenuation DOUBLE PRECISION DEFAULT \'NULL\', CHANGE proc_chance proc_chance DOUBLE PRECISION DEFAULT \'NULL\', CHANGE release_date release_date VARCHAR(255) DEFAULT \'NULL\', CHANGE vault_date vault_date VARCHAR(255) DEFAULT \'NULL\', CHANGE damage_per_shot damage_per_shot LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\', CHANGE parents parents LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE accuracy accuracy DOUBLE PRECISION DEFAULT \'NULL\', CHANGE multishot multishot DOUBLE PRECISION DEFAULT \'NULL\', CHANGE noise noise VARCHAR(255) DEFAULT \'NULL\', CHANGE trigger_type trigger_type VARCHAR(255) DEFAULT \'NULL\', CHANGE reload_time reload_time DOUBLE PRECISION DEFAULT \'NULL\'');
    }
}
